package github;

import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;

public class GitHubSSHKeyTest 
{

    RequestSpecification requestSpec;
    String sshKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv3ra8QBICJZz04pfHIVIQ+Hp0BPfZLV/6/EIsseXR4qzx8bLDGLs7za+cLMK0YPTdZVhyBQVlMjEYsSWLO1UbbbtQhMoASFmjoSRXnX5eOrHoojN9YllMdNeKl0nBHorSiolobI+J3EKccuIP4cui02Lg6QgZZXaBo2uRssOsBPdjtcH6VYTW8fpNO6CHU0DbVX/ePQB3LxH9C/Nx2f4USjYPdQaJOZnx6OSmlgWs0gBzHwRHVNYsRAToNWIuBPQuKY02oz/cYflGf6zt7qj+Am0cnOUDfXkGbr3uwPYEJ+ShglYnwske7zU8F+lNRmxT2805L4JKd7QN4jIkvBh9 Generated by ShowDNS - 2026-01-14";
    int keyId;

    String token = "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";

    @BeforeClass
    public void setup() 
    {
        requestSpec = new RequestSpecBuilder()
                .setContentType(ContentType.JSON)
                .addHeader("Authorization", "Bearer " + token)
                .addHeader("Accept", "application/vnd.github+json")
                .addHeader("User-Agent", "RestAssured-Test")
                .setBaseUri("https://api.github.com")
                .build();
    }

    @Test(priority = 1)
    public void authCheck() 
    {
        Response response = RestAssured.given(requestSpec)
                .get("/user");

        Reporter.log("AUTH CHECK RESPONSE:\n" + response.asPrettyString());
        Assert.assertEquals(response.getStatusCode(), 200, "Auth check failed");
    }

    @Test(priority = 2)
    public void addSSHKey() 
    {
        Map<String, String> requestBody = new HashMap<>();
        requestBody.put("title", "TestAPIKey");
        requestBody.put("key", sshKey);

        Response response = RestAssured.given(requestSpec)
                .body(requestBody)
                .post("/user/keys");

        Reporter.log("POST RESPONSE:\n" + response.asPrettyString());

        keyId = response.jsonPath().getInt("id");

        Assert.assertEquals(response.getStatusCode(), 201, "Failed to add SSH key");
        Assert.assertTrue(keyId > 0, "Key ID not returned");
    }

    @Test(priority = 3, dependsOnMethods = "addSSHKey")
    public void getSSHKey() 
    {
        Response response = RestAssured.given(requestSpec)
                .pathParam("keyId", keyId)
                .get("/user/keys/{keyId}");

        Reporter.log("GET RESPONSE:\n" + response.asPrettyString());
        Assert.assertEquals(response.getStatusCode(), 200, "Failed to get SSH key");
    }

    @Test(priority = 4, dependsOnMethods = "addSSHKey")
    public void deleteSSHKey() 
    {
        Response response = RestAssured.given(requestSpec)
                .pathParam("keyId", keyId)
                .delete("/user/keys/{keyId}");

        Reporter.log("DELETE STATUS CODE: " + response.getStatusCode());
        Assert.assertEquals(response.getStatusCode(), 204, "Failed to delete SSH key");
    }
}
